# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTE5Y2EyMTRhNWI2YTZmMjIxZGJmZjliN2YxMWY3Y2MwZGJjZjgwMjYyNGI4NTcyNGVjZjRhMGY5YmY2YjIyZTg4ZTFjZjExMWI0OWM1NzRlMzgwOWM3ZjlkMWVlZTkzOTUyZDBiOTE3YzM1YmRmZDQzZTBhM2RjZmUwMmNmZGY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
